export const projects = [
  {
    focus: 'Mobile/Responsive Design',
    title: 'Tic-Tac-Toe',
    deployed: '',
    repo: '',
    tags: 'Mobile-Design Responsive-Design JavaScript HTML CSS jQuery Bootstrap Algorithms Ruby Rails Logic',
    description: [
      'Bootstrap Mobile Friendly, Responsive',
      'Recursive Algorithm for Tic Tac Toe of any size',
      'Completed project within 4 business days',
      'Bonus Features: Undo move, Retrieve a previous game, Render previous games'
    ]
  },
  {
    focus: 'CSS Animations, Bootstrap Components, and Styling',
    title: 'Portfolio',
    deployed: '',
    repo: '',
    tags: 'JavaScript HTML CSS jQuery Bootstrap Animations Animate.css Keyframes Handlebars.js Moment.js',
    description: [
      'Utilizes Bootstrap Carousel, Tooltip, Card, Collapse, Modal, Scrollspy',
      'Includes multiple sections generated by Handlebars.js',
      'Includes custom-made slideshow, and up-down buttons'
    ]
  },
  {
    focus: 'Team Project',
    title: 'LetterBox: A text-only social media platform for cat lovers',
    deployed: '',
    repo: '',
    tags: 'JavaScript HTML CSS Ruby Rails Handlebars.js Agile Scrum Teamwork',
    description: [
      'Many One to Many Relationships',
      'Coordinated with team using Agile methods',
      'Completed code reviews and standups beginning of business day, mid-business day, and pre day end',
      'Completed project within 3 business days',
      'Bonus Features: Search, Like Resource, Card Collapse'
    ]
  },
  {
    focus: 'Front End Features',
    title: 'Brain Age',
    deployed: '',
    repo: '',
    tags: 'Logic Puzzle JavaScript HTML CSS jQuery Bootstrap Algorithms Ruby Rails Graph Handlebars.js',
    description: [
      'Game inspired by Brain Age for the Nintendo DS',
      'Implemented a Procedural Generation Algorithm that produces multiple choice logic',
      'Efficiently utilized existing Node packages such as Math.js and Chart.js to optimize time management',
      'Multple pages effect with jQuery hide/show',
      'Completed project within 4 business days',
      'Table generated with Handlebars.js'
    ]
  },
  {
    focus: 'Back End Features',
    title: 'StackOverKo',
    deployed: '',
    repo: '',
    tags: 'JavaScript HTML CSS Ruby Rails React.js',
    description: [
      'Many One to Many Relationships',
      'Model View Controller',
      'Serialize nested associations',
      'Custom routes and custom serializers'
    ]
  }
]
